### ISSUE TITLE
Allied Vision camera first read always fails

### ISSUE THREAD

**Issue by jmilloy** [genicam/harvesters#154] opened 2020-05-04 15:38 UTC
**Describe the bug**

After connecting to the camera (creating an ImageAcquirer), the first access always fails, no matter what it is. Subsequent io works, whether it is the same request or something else.

**To Reproduce**

Using an Allied Vision ALVIUM camera:

```
from harvesters.core import Harvester

h = Harvester()
h.add_file('/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti')
h.update()
ia = h.create_image_acquirer(0)
print(ia.remote_device.node_map.DeviceSerialNumber.value)
```

**Expected behavior**

The serial number should be printed

**Observed Behavior**

A GenTL io exception is raised:

```
Traceback (most recent call last):
  File "../test-harvesters.py", line 11, in <module>
    ia.remote_device.node_map.DeviceSerialNumber.value
  File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/genapi.py", line 2676, in _get_value
    return self._primal_get_value()
  File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/genapi.py", line 2652, in _primal_get_value
    return _genapi.IString__primal_get_value(self, Verify, IgnoreCache)
  File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/harvesters/_private/core/port.py", line 57, in read
    buffer = self.port.read(address, length)
  File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/gentl.py", line 5003, in read
    return _gentl.Port_read(self, address, buffer)
_gentl.IoException: GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Could not read data from 0x144(64 bytes). System error: 0x00000000, bytes received: 0) (ID: -1010)
```

**Desktop**
 - OS: Ubuntu 18.04
 - Python: 3.7.6
 - Harvester: 1.2.0
 - GenTL Producer: mvImpact-Acquire
 - Camera: Allied Vision Alvium

**Additional context**

* All subsequent camera io works, whether the same address or different addresses:

    ```
    >>> from harvesters.core import Harvester
    >>> h = Harvester()
    >>> h.add_file('/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti')
    >>> h.update()
    >>> ia = h.create_image_acquirer(0)
    >>> ia.remote_device.node_map.DeviceSerialNumber
    <genicam.genapi.IString; proxy of <Swig Object of type 'GENAPI_NAMESPACE::IString *' at 0x7f4e515d0210> >
    >>> ia.remote_device.node_map.DeviceSerialNumber.value
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/genapi.py", line 2676, in _get_value
        return self._primal_get_value()
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/genapi.py", line 2652, in _primal_get_value
        return _genapi.IString__primal_get_value(self, Verify, IgnoreCache)
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/harvesters/_private/core/port.py", line 57, in read
        buffer = self.port.read(address, length)
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/gentl.py", line 5003, in read
        return _gentl.Port_read(self, address, buffer)
    _gentl.IoException: GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Could not read data from 0x144(64 bytes). System error: 0x00000000, bytes received: 0) (ID: -1010)
    >>> ia.remote_device.node_map.DeviceSerialNumber.value
    '003G0'
    >>> ia.remote_device.node_map.DeviceVendorName.value
    'Allied Vision'
    ```

* The first camera io fails, whatever it is. So `DeviceVendorName.value`, `Height.get_access_mode()`, or `ia.start_acquisition` will trigger the io error, *if* it is the first attempted io (but then everything will work afterwards). Note that the second `start_acquisition` call works.

    ```
    >>> from harvesters.core import Harvester
    >>> h = Harvester()
    >>> h.add_file('/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti')
    >>> h.update()
    >>> ia = h.create_image_acquirer(0)
    >>> ia.start_acquisition()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/harvesters/core.py", line 2298, in start_acquisition
        buffer_size = self.remote_device.node_map.PayloadSize.value
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/genapi.py", line 2357, in _get_value
        return self._primal_get_value()
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/genapi.py", line 2273, in _primal_get_value
        return _genapi.IInteger__primal_get_value(self, Verify, IgnoreCache)
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/harvesters/_private/core/port.py", line 57, in read
        buffer = self.port.read(address, length)
      File "/home/jmilloy/miniconda3/envs/lmt/lib/python3.7/site-packages/genicam/gentl.py", line 5003, in read
        return _gentl.Port_read(self, address, buffer)
    _gentl.IoException: GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Could not read data from 0x20008(8 bytes). System error: 0x00000000, bytes received: 0) (ID: -1010)
    >>> ia.start_acquisition()
    >>> ia.is_aquiring()
    True
    ```

* Identical code for the FLIR BlackFly cameras does not have this problem. Those are the only two cameras I have here to test with.

**Comment by jmilloy** [comment] 2020-05-04 15:39
Is there just one more initialization step that I am missing?

**Comment by kazunarikudo** [comment] 2020-05-05 02:52
@jmilloy Hi, thank you for trying out Harvester. As far as I hear the symptom, I do not see any issue in your usage of Harvester. So I would suggest you the following idea: If you are involving cameras from several manufacturers, then try another version of MV's GenTL Producer. They have a website where you can download any version that they have released. Perhaps older versions do not reproduce the phenomenon but in general, they produce great software so I would not think they easily regress. However, sometimes it's cumbersome to tame USB3 host controllers or USB3 Vision devices/cameras in the transport layer level. Perhaps your host controller could be exposing an issue that MV has. If so, I would encourage you to report the issue to MV as a user; it's not bad deal, you use their software for free and they get an exposed issue that should be fixed. /Kazunari

**Comment by jmilloy** [comment] 2020-05-05 14:39
Ok, after some more testing, I can see that I have errors independent of harvesters. VimbaViewer can enumerate, connect, and configure, but not acquire; mvDeviceConfigure can enumerate and connect, but not configure or acquire; harvesters with the vimba cti file can enumerate, configure, and acquire, but can't connect using the serial number; and harvesters with the mv cti file can enumerate and connect, but is unstable (different errors at different times). I'll keep digging, but it seems that harvesters is not the problem. Thanks!

**Comment by StefanD986** [comment] 2020-05-06 12:02
Maybe this helps: I was using an Allied Vision camera sucessfully with the Matrix Vision GenTL producer 
(IIRC I installed mvGenTL_Acquire-x86_64-2.37.1.exe from http://static.matrix-vision.com/mvIMPACT_Acquire/)

**Comment by jmilloy** [comment] 2020-05-06 13:38
@StefanD986 Yeah, that's what I'm using originally, but then I also tested the vendor producer and even the vendor GUI and still had problems. I'm going to try everything on Windows instead of Ubuntu Linux today.

**Comment by kazunarikudo** [comment] 2020-05-27 01:40
Closing. Please feel free to re-open this when you get a clue the issue is caused by Harvester.

**Closed by kazunarikudo** 2020-05-27 01:40 UTC
