### ISSUE TITLE
License Agreement: MATRIX VISION mvAcquire GenTL file on ARM64

### ISSUE THREAD

**Issue by EnricoBeltramo** [genicam/harvesters#372] opened 2022-09-30 07:26 UTC
I tried to use the library on a Jetson Xavier ARM64 using mvAcquire of Matrix vision built for ARM64 and a lxg-20cp Baumer Camera. The library read and write fine parameters from camera, but when I try to acquire images I have an image with a moving text like that:
![acquisition](https://user-images.githubusercontent.com/22332651/193214026-9f429602-ca1e-4870-a2b4-95bfa7869e6d.jpeg)

In the past I used mvAcquire  driver with Linux and Windows x86 and I never had issue, may be someone else tried to run on ARM64 and know if there are specific licences to acquire o some more actions to do?

**Comment by kazunarikudo** [comment] 2022-10-01 13:30
@EnricoBeltramo Hi, thank you for trying out Harvester. Concerning the reported issue, it is not surprising because their license agreement should be respected. I recommend contacting MATRIX VISION sales if you are happy with the quality they can offer you. Thanks!

**Comment by kazunarikudo** [comment] 2022-10-01 13:32
@EnricoBeltramo Please feel free to close this ticket by yourself.

**Comment by MathijsNL** [comment] 2022-10-19 20:52
Why don't you use the Baumer CTI files instead? They are included in the gapi-sdk, also for ARM.
https://www.baumer.com/nl/en/product-overview/industrial-cameras-image-processing/software/baumer-gapi-sdk/linux-arm/c/14178

**Comment by EnricoBeltramo** [comment] 2022-10-19 21:15
Should be interesting, but I would to have an application that is compatible with different kinds of camera and I suppose that baumer driver works only with Baumer cameras, it's correct?

**Comment by vigneshgarrapally** [comment] 2023-01-11 16:10
I have been using SVS VISTEK camera which supports GENICAM standard. I have checked with them.  unfortunately, They don't have CTI file. I have contacted Matrix Vision sales team. Meanwhile, I am interested to know are there opensource ARM based CTI files which don't have trail period and can be used for any GENICAM supported camera?

**Comment by MathijsNL** [comment] 2023-01-11 22:18
They do have CTI files for x64 platform. Did they really confirm they don't have any support for arm?

https://www.svs-vistek.com/en/support/svs-support-download-center.php
![image](https://user-images.githubusercontent.com/1612886/211929305-275c3548-4fe2-4e1a-9b2b-b61d3dd11b3d.png)

```
SVCapture_Linux_ubuntu_18.04.5_x86-64_svn2548.tar.gz\SVCapture_Linux_ubuntu_18.04.5_x86-64_svn2548.tar\SVCapture2Setup_Linux_release\SVCamKit\SDK\Linux64_x64\cti\
libsv_gev_tl_x64.cti
libsv_u3v_tl_x64.cti

```

**Comment by PVTejas-Yottaasys** [comment] 2023-01-12 06:12
The did confirm they do not provide .cti files for ARM, only .so files.

**Comment by jcormier** [comment] 2023-01-12 13:38
On windows a cti file is just a renamed dll. Could the same be true for
linux? I'd try pointing harvested to the .so file and see what happens.

**Comment by kazunarikudo** [comment] 2023-01-13 00:37
> Could the same be true for linux?

Yes, it is true, too.

**Comment by kazunarikudo** [comment] 2023-01-13 00:39
> Baumer cameras, it's correct?

@EnricoBeltramo I have never confirmed the reality but it can be correct. It is not surprising to block other competitors.

**Comment by kazunarikudo** [comment] 2023-01-13 00:43
> The did confirm they do not provide .cti files for ARM, only .so files.

If the file is a GenTL Producer, then it must expose the defined C-API functions. If those functions are not exposed then it is just an image acquisition library. None of GenTL consumers such as Harvester can communicate with it.

I would not say anything much. It all depends on SVS-VISTEK's response.

**Comment by vigneshgarrapally** [comment] 2023-01-19 07:36
> > The did confirm they do not provide .cti files for ARM, only .so files.
> 
> If the file is a GenTL Producer, then it must expose the defined C-API functions. If those functions are not exposed then it is just an image acquisition library. None of GenTL consumers such as Harvester can communicate with it.
> 
> I would not say anything much. It all depends on SVS-VISTEK's response.

Thanks for your reply. If I understand correctly, Harvester (or any GenTL consumer) can be used to load a GenTL producer in any format( .cti or .so) if it has exposed defined C- API functions. 

R&D team from SVS-VISTEK had responded with the following information.
![image](https://user-images.githubusercontent.com/47147513/213382248-aadf99af-bd7a-4ef6-b596-4a9a3220771d.png)

**Comment by kazunarikudo** [comment] 2023-01-19 08:54
@vigneshgarrapally Hi, Harvester should be able to load the files marked as GenTL. If it can’t then it means I’ve injected a defect. If so then excuse me, I’ll fix that. However, I guess you know why but please note that you should load a file from the originally installed location.

**Closed** 2023-01-21 00:44 UTC
Labels: question, 3rd-party related

**Comment by StefanBattmer** [comment] 2024-04-26 07:14
Hi everyone,  I am one of the developers of the Impact Acquire SDK and even though this thread is quite old I would like to clarify what was discussed here to maybe help others stumbling on this later:

- Impact Acquire on ARM was never open for third party (thus non Balluff GmbH (formerly MATRIX VISION GmbH)) devices
- Impact Acquire since version 3.0.0 is also no longer open for third party devices on every other platform

So, these days running a third-party streaming device using our SDK requires the purchase of a runtime license. Non-streaming devices can still be operated free of charge, licenses can be obtained from the Balluff website. It was always our primary objective to provide an SDK that implements various vision standards in the best possible way to support EVERY device that complies with the standard. This is still true today. However the behaviour of a small selection of certain device vendors out there left us with no other choice then giving up that open SDK approach. I personally think this is a pity it but became unavoidable at a certain point.

So all that’s left to say would be: Our SDK still rocks! You get your money’s worth! 😉
