### ISSUE TITLE
GUI that controls camera with harvester module hangs up unexpectedly

### ISSUE THREAD

**Issue by thanos91** [genicam/harvesters#156] opened 2020-05-10 09:37 UTC
I have implemented a class that is responsible for shooting images using your very helpful module.
I use this class in a GUI built with PyQt5 and occasionally with the pressing of a button in the GUI i acquire an image. Sometimes the GUI freezes and i have to completely terminate the program and restart it. I think that this is related to the question @molron asked. The implemented class that uses much of the code you kindly provided is as follows. Is there any way that can assure that the program is not left hanging?

```python
class Controller:
    def __init__(self):
        self.h = Harvester()
        self.h.add_cti_file((Path(ROOT_DIR) / 'ctis' / "bgapi2_gige.cti").as_posix())
        self.h.update_device_info_list()
        print(len(self.h.device_info_list))
        self.ia = self.h.create_image_acquirer(0)

        self.ia.device.node_map.Width.value = 5472
        self.ia.device.node_map.Height.value = 3648

        self.ia.device.node_map.PixelFormat.value = 'BayerRG8'
        # ia.device.node_map.AcquisitionMode.value = 'Continuous'
        # self.ia.device.node_map.AcquisitionMode.value = 'SingleFrame'
        self.ia.start_image_acquisition()

    def shoot_image(self):
        print(self.ia, type(self.ia))
        print(self.ia.num_buffers)

        with self.ia.fetch_buffer() as buffer:
            print(buffer)
            component = buffer.payload.components[0]
            data_format = component.data_format
            print(data_format)
            if data_format in mono_location_formats or bayer_location_formats:
                print(len(component.data))
                content = component.data.reshape(component.height, component.width).copy()

            elif data_format in rgb_formats or \
                    data_format in rgba_formats or \
                    data_format in bgr_formats or \
                    data_format in bgra_formats:
                #
                content = component.data.reshape(
                    component.height, component.width,
                    int(component.num_components_per_pixel)  # Set of R, G, B, and Alpha
                ).copy()
                print(content.shape)
            # ia.stop_image_acquisition()
            else:
                print('dindnt go to bayer')


            return content

    def shoot_image_safe(self):
        try:
            return self.shoot_image()
        except Exception as e:
            print(e)
            self.close_connection()
            self.__init__()
            return self.shoot_image()

    def close_connection(self):
        self.ia.destroy()
        self.h.reset()
```

**Comment by kazunarikudo** [comment] 2020-05-10 13:26
@thanos91 Hi, thank you for trying out Harvester.

> the pressing of a button in the GUI i acquire an image.

(1) Pushing the button is the only way to reproduce the phenomenon? (2) Could you show me the code that is called when you push the button? Is that the `shoot_image_safe`?

One thing I can guess is there's a case where the GenICam Python binding, `genicam` package hangs. Perhaps I could ask you to collect information to debug the issue. /Kazunari

**Comment by thanos91** [comment] 2020-05-10 14:10
You are exactly right. In the GUI when you press the button **CAPTURE**, i invoke the  _shoot_image_safe_ function. I strongly believe that this issue is related to #105 . As i use this code to a production environment i would like a way to gracefully capture this unexpected behavior and restart the Harvester object. By the way i think that the function _shoot_image_safe_, as i have implemented it fails to handle this.

**Comment by kazunarikudo** [comment] 2020-05-10 14:40
@thanos91 Could you call the method instead of `shoot_image_safe` and check if the phenomenon can be reproduced, please? It might take time but it can reproduce the phenomenon I'd dig in the `geincam` package:

```
def dummy(self):
    for i in range(100):
        _ = self.ia.remote_device.node_map.PixelFormat.value
        _ = self.ia.remote_device.node_map.Width.value
        _ = self.ia.remote_device.node_map.Height.value
```

PS. Note that you need to call `remote_device` property if you want to access to GenICam feature nodes in the camera. `device` points at a local device module of the GenTL Producer and it's another entity. I made the change to resolve #84.

**Comment by thanos91** [comment] 2020-05-10 14:55
@kazunarikudo Thank you for your replies. As i have limited access to the physical device, i will come back to you when i have run the code you suggested

**Comment by kazunarikudo** [comment] 2020-05-10 15:01
@thanos91 Oh, I'd be glad if you can make a try when you can. Harvester is my 100% private project so I cannot work for it in the daytime, either. If the issue is coming from the `genicam` package the issue would be significant so I would like to take the issue seriously.

**Comment by thanos91** [comment] 2020-05-11 15:54
@kazunarikudo I have done the following modifications. I have updated the harvesters library from 0.2.18 version (i think) to 1.2.0, and followed the method updates that you specified. I have run the dummy function you specified and the code run smoothly. I also tried to take photos at random intervals and things seem to be going well. If the end user runs into any troubles again, i'll reach out to you for some directions. Thank you for your time. Cheers!

**Comment by kazunarikudo** [comment] 2020-05-11 15:56
@thanos91 Okay, so I'm going to close this ticket but please feel free to reopen when the issue came back. /Kazunari

**Closed by kazunarikudo** 2020-05-11 15:56 UTC

**Comment by thanos91** [comment] 2020-05-13 09:10
@kazunarikudo There are some new updates. To provide some more information, i use a Baumer camera and i am interested in **SingleFrame image acquisition**. My python code (with the new modifications) is as follows:
```python
class Controller:
    def __init__(self):
        self.h = Harvester()
        self.h.add_file(str(Path('Bin') / "bgapi2_gige.cti"))
        self.h.update()
        print(len(self.h.device_info_list))
        self.ia = self.h.create_image_acquirer(0)

        print(dir(self.ia))

        self.ia.remote_device.node_map.Width.value = 5472

        self.ia.remote_device.node_map.Height.value = 3648

        self.ia.remote_device.node_map.PixelFormat.value = 'BayerRG8'
        # self.ia.remote_device.node_map.AcquisitionMode.value = 'Continuous'
        # self.ia.remote_device.node_map.AcquisitionMode.value = 'SingleFrame'


    def shoot_image(self):
        print(self.ia, type(self.ia))
        print(self.ia.num_buffers)
        self.ia.start_acquisition()

        with self.ia.fetch_buffer() as buffer:
            print(buffer)
            component = buffer.payload.components[0]
            data_format = component.data_format
            print(data_format)
            if data_format in mono_location_formats or bayer_location_formats:
                print(len(component.data))
                content = component.data.reshape(component.height, component.width).copy()

            elif data_format in rgb_formats or \
                    data_format in rgba_formats or \
                    data_format in bgr_formats or \
                    data_format in bgra_formats:
                #
                content = component.data.reshape(
                    component.height, component.width,
                    int(component.num_components_per_pixel)  # Set of R, G, B, and Alpha
                ).copy()
                print(content.shape)
                self.ia.stop_acquisition()
            else:
                print('dindnt go to bayer')

            return content

    def shoot_image_safe(self):
        if self.ia is None:
            print('ton ipiame')
        try:
            return self.shoot_image()
        except Exception as e:
            print(e)
            self.close_connection()
            self.__init__()
            return self.shoot_image()

    def close_connection(self):

        self.ia.destroy()
        self.h.reset()
```
This code always throws an Exception
GenTL exception: Operation cannot be performed. Responsible module is busy. (Message from the source: Unsupported info parameter) (ID: -1022)

**Comment by thanos91** [comment] 2020-05-13 10:27
@kazunarikudo 
By creating the ImageAcquirer object in the ```shoot_image``` method, with a code like
```python
with self.h.create_image_acquirer(0) as ia:
    ia.start_acquisition()
    with ia.fetch_buffer() as buffer:
```
all things run smoothly. I thought that you don't need to destroy the ImageAcquirer object and initiate it again each time you want to take a photo. Am i wrong?
