### ISSUE TITLE
Acquisition using two Sony XCG-CG510C cameras simultaneously

### ISSUE THREAD

**Issue by AliaMoha** [genicam/harvesters#328] opened 2022-03-31 07:26 UTC
Hi,

I am are trying to use two Sony cameras for a stereo vision approach. Using only one camera, the acquisition seems to be working fine.  When I create a second ImageAquirer the acquisition gets stuck after a few frames, even while fetching only from one camera.
As a minimal example, I'm basically just trying to fetch images from two different cameras as follows:
<details>
<summary>Minimal example with 2 acquirers</summary>

```
   
    h = Harvester()
    h.add_file('C:/Program Files/Baumer_GAPI_SDK_2.12.0/bin/bgapi2_gige.cti')
    h.update()

    print('Harvesters Version: ', __version__ )
    print(*h.device_info_list,sep='\n')
   
    
    ia0 = h.create(0)
    ia0.remote_device.node_map.get_node('AcquisitionMode').value = 'Continuous'
   
    ia1 = h.create(1)
    ia1.remote_device.node_map.get_node('AcquisitionMode').value = 'Continuous'
   
    ia0.start(run_as_thread=True)
    ia1.start(run_as_thread=True)

    while cv2.waitKey(1) != 27 :

                with ia0.fetch() as buffer0:
                    pl = buffer0.payload
                    co = pl.components[0]
                    wi = co.width
                    he = co.height
                    content = co.data.reshape(2048,2448)
                    print(f'Time: {time.time() - start:.2f}  Cam 0')
     
                with ia1.fetch() as buffer1:
                    pl = buffer1.payload
                    co = pl.components[0]
                    wi = co.width
                    he = co.height
                    content = co.data.reshape(2048,2448)
                    print(f'Time: {time.time() - start:.2f}  Cam 1' )

            except Exception as ex:
                print(ex)
    finally:
        ia0.stop_acquisition()
        ia0.destroy()
        ia1.stop_acquisition()
        ia1.destroy()
        h.reset()
```
</details>

The code generates the following output. Note that the execution is stuck after a few seconds. 

<details>
<summary>Output of the minimal example</summary>

```
Harvesters Version:  1.3.5

{'access_status': 1, 'display_name': 'eth2', 'model': 'XCG-CG510C', 'parent': <genicam.gentl.Interface; proxy of <Swig Object of type 'std::shared_ptr< GenTLCpp::TLInterface > *' at 0x00000258781A6840> >, 'tl_type': 'GEV', 'user_defined_name': None, 'vendor': 'SONY', 'version': None}

{'access_status': 1, 'display_name': 'eth3', 'model': 'XCG-CG510C', 'parent': <genicam.gentl.Interface; proxy of <Swig Object of type 'std::shared_ptr< GenTLCpp::TLInterface > *' at 0x00000258781A6C30> >, 'tl_type': 'GEV', 'user_defined_name': None, 'vendor': 'SONY', 'version': None}

Time: 0.86  Cam 0
Time: 0.92  Cam 1
Time: 1.19  Cam 0
Time: 2.63  Cam 1
Time: 2.65  Cam 0
```
</details>

**Configuration**

 - OS: Windows 10
 - Python: 3.8
 - Harvester: 1.3.5
 - GenTL Producer: Baumer
 - Camera: Sony XCG-CG510C
 
The cameras are connected via PCIe Controller with separate subnets assigned and Jumbo-frames active. I have been working with the same setup and configuration using a C++ interface, so I know that the hardware can provide enough throughput. 
 
**Actions You Have Taken**

I have tried multiple versions of harvesters with different producers, but the problem persists.

* harversters 1.3.2, 1.3.5 
* Python 3.6, 3.8
* GenTL Producer: Baumer, Matrix Vision

What I also tried:
* decreasing the image resolution
* decreasing the rate of fetch calls
* creating multiple harvester cores and assigning multiple ctis
* trying different settings for the Acquisition mode 

**Additional context**
Issue #264 seems related, but does not provide additional information.

Thank you for your time.
Regards, AliaMoha

**Comment by kazunarikudo** [comment] 2022-03-31 13:41
Hi, thank you for the report. Okay, so could you try to run a script to log the events.

Please find attached, the package consists of two files: (1) A test script, test_328.py, and (2) a logging configuration file, logging.report.ini. The test script creates an ImageAcquirer object for every available device on the system and lets them keep running until they acquire 10 images. (If 10 is not enough to reproduce the phenomenon, please feel free to increase the number.)

To get the script running, you will need to set three environment variables:

1. `HARVESTERS_TEST_TARGET`: Specify a path to the target GenTL Producer file (*.cti),
2. `HARVESTERS_LOGGING_CONFIG`: Specify a path to the logging config file, (*.ini), and
3. `HARVESTERS_LOG_BUFFER`: No value is required, just define it.

Please place them wherever you prefer, and then execute the following command; I assume that you're running the script on a WIndows:

```
set HARVESTERS_TEST_TARGET=path/to/your.cti & set HARVESTERS_LOGGING_CONFIG=path/to/logging.report.ini & set HARVESTERS_LOG_BUFFER= & python -m unittest path/to/test_328.py > path/to/test_328.log
``` 

The last part, `> path/to/test_328.log` is necessary only when you prepare a log file for me. Please make sure you can get a valid output and then show me the result by attaching it to the following comment block.

As far as I tried to run the script with two GenTL Producer simulators and a GEV GenTL Producer, I could not reproduce the phenomenon. So there would be a key factor in your setup. I hope Harvester can work for your project and let's see what the outcome is.

Thanks, Kazunari.

[328.zip](https://github.com/genicam/harvesters/files/8389765/328.zip)

**Comment by kazunarikudo** [comment] 2022-10-01 14:44
Closing. Please feel free to reopen if needed.

**Closed by kazunarikudo** 2022-10-01 14:44 UTC
