### ISSUE TITLE
Euresys coaxlink + TDI camera cannot work under 'Area' mode

### ISSUE THREAD

**Issue by YujieShen** [genicam/harvesters#155] opened 2020-05-08 22:46 UTC
**Is your feature request related to a problem? Please describe.**
Euresys offers the 'Area mode' operation for TDI cameras, which allows TDI to work like normal cameras. However, harvesters fetch_buffer() method always return a buffer with height 1--- which is the camera 'Height'. Therefore can only retrieve the first line of the image.

**Describe the solution you'd like**
Use 'BufferHeight' from datastream as the height of the buffer not camera height, when operating in 'Area' mode.

**Comment by kazunarikudo** [comment] 2020-05-08 23:40
@YujieShen Hi, thank you for your comment. Could you tell me which GenICam feature node can I check if the camera is running in `Area` mode? /Kazunari

**Comment by YujieShen** [comment] 2020-05-09 00:37
@kazunarikudo Hi, thanks for the prompt reply. Euresys had it in 'Remote Devices'->'OperationMode' (which allows one to choose between 'TDI' and 'Area'); and the actual height is in 'Data Streams'->'BufferHeight'. Thanks, and please let me know if there's anything unclear /Yujie

**Comment by kazunarikudo** [comment] 2020-05-09 01:24
@YujieShen Thank you for your reply. Sounds like `OperationMode` is a custom feature node but I guess Harvester should be able to handle `TDI`/`Area` as long as `BufferHeight` indicates an appropriate value. (1) Is the value of `BufferHeight` updated when `OpetaionMode` is overwritten/changed? One thing I feel a bit strange is the height has been applied a value that is not appropriate from your point of view even though I can see Harvester should refer to a value that is returned from the `BUFFER_INFO_HEIGHT` command of `DSGetBufferInfo` function. In the current implementation, Harvester applies the value that is returned from the `BUFFER_INFO_HEIGHT` command of `DSGetBufferInfo` function and if it's not supported then it refers to the `Height` value of the remote device as an alternative. Perhaps it could be helpful if you show me a screenshot of the feature grid, a table-look-like GUI that allows users to change node values, that displays the members of the GenTL Buffer module.

**Comment by YujieShen** [comment] 2020-05-09 03:01
<img width="1920" alt="euresys harvesters buffer issue" src="https://user-images.githubusercontent.com/40870735/81462251-126c4a80-9166-11ea-858e-7c7c555a06b7.png">
Hi @kazunarikudo . BufferHeight variable won't change when operationmode is changed (at least not in the GeniCam application came along with Euresys driver). And it seems like I've got the wrong impression--- fetch_buffer() actually returned me with a 4640x0 image (so no data). I've attached a screenshot during debug, which showed that _buffer actually contained the 4640x256 data (delivered image height was 256 which was correct), but the buffer itself was interpreted as 4640x0. Wondering if this is an issue you've seen before?

**Comment by kazunarikudo** [comment] 2020-05-10 13:34
@YujieShen Hi, thank you for the information. Okay, I will look into it and get to you back once I get something to be discussed with you.

**Comment by YujieShen** [comment] 2020-05-10 17:30
@kazunarikudo Thanks a lot! I'll also keep trying on my side to see if there's anything I can do to fix this.

**Comment by YujieShen** [comment] 2020-05-11 02:54
Hi @kazunarikudo . I did a bit more experiment and obtained some more clues. Euresys provides a background log showing the commands and failures. I've captured a successful grab using their own Genicam software, and a failed grab using the example Python program. So what I noticed is that EventGetData in the log started reporting timeout errors after ia.start_acquisition() is executed. And if I compare the successful run to the failed one, the iTimeout passed to EventGetData were different. Just wondering if this might be the cause, and where can I find this parameter in the Python package? Thanks.
![failed](https://user-images.githubusercontent.com/40870735/81520065-0a441480-92f8-11ea-83bf-42416f4760af.PNG)
![successful](https://user-images.githubusercontent.com/40870735/81520071-0f08c880-92f8-11ea-9439-1a19bb546532.PNG)

**Comment by kazunarikudo** [comment] 2020-05-11 02:59
@YujieShen Thanks for the update. Could you tell me which version of Harvester that you're working with now?

**Comment by YujieShen** [comment] 2020-05-11 03:04
@kazunarikudo It's 1.2.0 I believe

**Comment by kazunarikudo** [comment] 2020-05-11 03:07
@YujieShen Okay, so how do you call `ia.start_acquisition()`? Are you passing any parameter?

**Comment by YujieShen** [comment] 2020-05-11 03:11
@kazunarikudo So I tried two methods: 1. not passing anything, and 2. passing (run_in_background=True). But both gave the same result.

**Comment by kazunarikudo** [comment] 2020-05-11 03:14
@YujieShen In general, it's not necessary to pass `run_in_background=True`. It lets the image acquisition thread in the background. Even if you did not pass that parameter, i.e., you called literally `ia.start_acquisition()` you would see the difference in the `iTimeout`?

**Comment by YujieShen** [comment] 2020-05-11 03:17
Hi @kazunarikudo  No, iTimeout always appeared to be 1

**Comment by kazunarikudo** [comment] 2020-05-11 03:23
@YujieShen So could you call `ia.timeout_for_image_acquisition = -1` before starting image acquisition and tell me what happened as the result?

**Comment by YujieShen** [comment] 2020-05-11 15:52
Hi @kazunarikudo , thanks for the advice. So setting this to -1 gave me an overflow error in the method 'EventManagerNewBuffer_update_event_data'. I tried increasing this value to 1000 and that clears the error for timeout, but I'm still getting empty buffer:
![halfway](https://user-images.githubusercontent.com/40870735/81581688-e74f4a00-9363-11ea-9e79-843b2420958c.PNG)
So I did a more careful comparison between the commands and noticed two major differences:
1. There is a 'GenapiExecuteCommand(..., AcquisitionStart)' called before DSStartAcquisition, and correspondingly a GenapiExecuteCommand(..., AcquisitionStop)' after DSStopAcquisition. I'm not sure if this is a Euresys specific implementation or is it a general GeniCam feature? Maybe it's used to tell the camera to start acquisition?
2. Euresys used DSAllocAndAnnounceBuffer instead of DSAnnounceBuffer, does the two have the same effect?

**Comment by YujieShen** [comment] 2020-05-12 02:42
Hi @kazunarikudo . I checked with Euresys engineers and they believe it is still the buffer height setting that's giving me this error. I'm pasting it below in case this will help:
"_the issue is that harvester use the Height parameter of the camera. For a line scan camera this parameter should be 0 ( some camera manufacturer set 1)
When harvester allocated the buffer Width * Height =0 so no buffer are allocated 
Somehow ( and I don’t know where) Harvester should not use Height if Height <=1 but use BufferHeight that is a data stream parameter.
In this case ( on Harvester point of view) we are back to a Areascan mode and acquisition should work well._"

**Comment by kazunarikudo** [comment] 2020-05-12 03:28
@YujieShen Thank you for the update, I will look into it when I am available and will let you know once I made a progress. Excuse me, Harvester is one of my private projects so I'm not allowed to work for it while I am working for a regular job. /Kazunari

**Comment by kazunarikudo** [comment] 2020-05-12 13:10
@YujieShen Hi.

> _"Harvester should not use Height if Height <=1 but use BufferHeight that is a data stream parameter."_

I have just looked through the screenshot that you showed me but the value returned from the GenTL Producer was 0 even though I expected to see a value that is > 1; the value of `genicam.gentl.Buffer.height` is read as a return from `BUFFER_INFO_HEIGHT`.

The comment above from the engineer sounds as if I can see a value that is > 1 but it's 0 in reality. Do you have any idea about this? I admit the possibility of a case where the issue is coming from Harvester but if the error permanently happens then other people should give me the same report.

If you can find the right value from the `genicam.gentl.Buffer` object please let me know.

**Comment by YujieShen** [comment] 2020-05-13 15:10
Hi @kazunarikudo . Buffer is still like the earlier screen I shared. The debug is always outside _gentl.pyd so I don't know why every time it gets new buffer the height is wrong. Also the chunk data info list gives an error saying no data to work with. So probably it is something intrinsic with python Genicam on TDI cameras? Wondering if you've seen successful runs with other line cameras?

**Comment by kazunarikudo** [comment] 2020-05-14 14:03
@YujieShen Hi. I have just noticed a property called `delivered_image_height` was saying `256`. Is that the value that you wanted to get? I have just committed a change to branch `_issue_155`. Could you try that out when you can, please? In addition, I would appreciate it if you could as Euresys people how should I retrieve the right value. As we have seen there are several parameters such as `BUFFER_INFO_HEIGHT ` or `BUFFER_INFO_DELIVERED_IMAGEHEIGHT  ` but the GenTL Standard does not say about any possible order. Thanks. /Kazunari

**Comment by YujieShen** [comment] 2020-05-15 05:04
Hi @kazunarikudo  It worked! I was able to get the desired buffer and convert it into image. I'll do a hardware test for video acquisition early next week and will let you know the final result. Thanks a lot for the help!
BTW, I noticed in the branch you had the code added to the width() function, so I changed it to height()

**Comment by kazunarikudo** [comment] 2020-05-15 05:44
@YujieShen Hi, thank you for your reply. It's good to know that it worked for you.
> BTW, I noticed in the branch you had the code added to the width() function, so I changed it to height()

Ah, okay, I'll fix that and push the commit to the development branch. /Kazunari

**Comment by kazunarikudo** [comment] 2020-05-15 12:43
@YujieShen Hi, have just fixed that. Thanks.

**Comment by kazunarikudo** [comment] 2020-05-18 14:04
@YujieShen It's not urgent but I'll be waiting for the final result from you. Thanks. /Kazunari

**Comment by YujieShen** [comment] 2020-05-18 15:44
Hi @kazunarikudo  Sorry for the delay. Yes I've confirmed that it could grab and stream the image correctly.

**Closed** 2020-05-18 15:44 UTC
