### ISSUE TITLE
Low acquisition framerate (Mono16) 

### ISSUE THREAD

**Issue by ThermoGnad** [genicam/harvesters#171] opened 2020-06-03 14:34 UTC
Hello kazunarikudo,
My current problem is related to issu #131 
Unfortunately, I don't get higher framerates than around 20FPS (If the desired framrate is set to any value lower than 20 it works accurate.)
To acquire and store frames in RAM i use:
`for i in range(n_frames):`
`   with ia.fetch_buffer() as buffer:`
`      np.copyto(frames[i], buffer.payload.components[0].data.reshape(buffer.payload.components[0].height, buffer.payload.components[0].width))`
after finishing acqisition I save the frames to Disk.

**Desktop (please complete the following information):**
OS: Windows 10, 64 bit
Python: Python 3.6.8
Harvester: 1.2.3
GenTL Producer: Matrix Vision
Camera: IRS640, (Automation Technology), Mono16, nominal FPS: 94.8 (due to ROI)

**Comment by kazunarikudo** [comment] 2020-06-03 14:51
@ThermoGnad Hi. Thank you for creating another ticket. Okay, so how much frame rate would you get if you do not call `np.copyto()`?

**Comment by ThermoGnad** [comment] 2020-06-03 15:14
Hi. Without the `np.copyto()` there is no big difference.
I made a more accurate measurement (acquired 1000 frames): 
- without np.copyto(): 29.3 fps
- with np.copyto(): 29.25 fps (sorry for the wrong framerate in the initial post)

**Comment by kazunarikudo** [comment] 2020-06-03 15:31
@ThermoGnad Thank you for the update. Sorry for having asked you so many questions, what would happen if the pixel format was Mono8? (I'm not sure if your camera supports it though.)

**Comment by kazunarikudo** [comment] 2020-06-03 15:34
@ThermoGnad One more thing, could you show me the line where you call `start_acquisitoin` method, please?

**Comment by ThermoGnad** [comment] 2020-06-03 15:53
@kazunarikudo 
Unfortunately, my camera does not support Mono8.

my script is nearly the same as the script of bobcorn. The funktion  startig acquisition:

`def init_camera(fps):
    ia = None

    h = Harvester()
    h.add_cti_file(SDK_CTI_PATH)
    h.update_device_info_list()

    try:
        ia = h.create_image_acquirer(serial_number=CAMERA_SN)
    except:
        print("[ERROR] Camera with specified model \"" + CAMERA_SN + "\" is busy or not connected.")
        exit(1)

    ia.remote_device.node_map.Width.value = WIDTH
    ia.remote_device.node_map.Height.value = HEIGHT
    ia.remote_device.node_map.PixelFormat.value = PIXEL_FORMAT
    ia.remote_device.node_map.AcquisitionFrameRate.value = fps

    ia.start_acquisition()

    return h, ia`

calling the this just before fetching the buffer:

`    h, ia = init_camera(fps)`

**Comment by kazunarikudo** [comment] 2020-06-04 02:46
@ThermoGnad Thank you for the update. Okay, so could you check if you can acquire images at 90 fps using another library? I fell a bit strange because you can acquire images, I mean valid images that are not `None`. It means Harvester has interpreted the delivered data in the declared pixel format. And you are trying to acquire Mono16 images and it's one of simple pixel data formats like Mono8. I have confirmed Harvester can acquire Mono8 at about 200 fps for a 4M pix image. So I would expect you should be able to acquire the images at 90 fps as you exact. Of course, I admit you are facing the issue anyway and there must be a reason that brings up the result.

**Comment by kazunarikudo** [comment] 2020-06-04 03:16
@ThermoGnad I have just checked out AT's flyer for IRS640 at [here](https://www.automationtechnology.de/cms/wp-content/uploads/2018/11/IRSX-Series_web.pdf). I am not willing to stick my mind on Mono8 but the flyer seems to be saying it supports 8-bit output (I'm not sure if it's Mono8, to be honest). Please never mind if it does not support Mono8 anyway. However, again, even if the pixel format was Mono16, it is strange to hear the frame rate is limited to about 20 fps for an image that is smaller than VGA. I guess you should be able to acquire a mono VGA image at about 340 fps on gigabit Ethernet. Even if the format was Mono16, 20 fps is much smaller.

**Comment by kazunarikudo** [comment] 2020-06-09 08:55
@ThermoGnad Thank you for the update. I would not stick my mind on Mono8 but would be able to try with another model so that you can acquire images at the frame rate that you expected?

**Comment by ThermoGnad** [comment] 2020-06-09 12:21
@kazunarikudo Contacting AT seems to be the best idea, especially if they konw you and harvesters.
Futhermore, I have a Flir A35, running with 60fps (Mono8, Mono14, Mono16)
Unfortunately, this one is not working at all with harvesters:
`  File "C:\...\venv\lib\site-packages\harvesters\core.py", line 2484, in fetch_buffer
    raise TimeoutException
_gentl.TimeoutException`
I think it is because that camera has noch bool if it is acquiring? (Acquisition with Matlab working stable)
I will try to call Stephan know...

**Comment by ThermoGnad** [comment] 2020-06-09 12:31
@kazunarikudo Update for you: Stephan is currently on vacation. But his collegue will call me back to discuss the problem.
(For your personal interest: Stephan K. is now Stephan R., he recently married) ;)

**Comment by kazunarikudo** [comment] 2020-07-21 13:44
Closing. Please feel free to reopen this ticket if there's a bug.

**Closed by kazunarikudo** 2020-07-21 13:44 UTC
