### ISSUE TITLE
genicam package for python 3.8

### ISSUE THREAD

**Issue by jcormier** [genicam/harvesters#125] opened 2020-03-16 16:28 UTC
**Describe the bug**
Just installed python via anaconda and got python version 3.8.1.  Using this version pip cannot find the genicam package.

**To Reproduce**
1. pip install genicam
ERROR: Could not find a version that satisfies the requirement genicam (from versions: none)
ERROR: No matching distribution found for genicam
python -V
Python 3.8.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python: 3.8.1
 - Harvester: 1.1.0

**Comment by kazunarikudo** [comment] 2020-03-16 16:39
@jcormier Hi. Thank you for the report. Unfortunately, the latest `genicam` package has not supported Python 3.8 yet. However, I have already ported it to 3.8 and it will be released when the next GenICam reference implementation is released. Its release date has not been officially scheduled yet but I guess it will be some time this year. Sorry for the inconvenience! /Kazunari

**Comment by jcormier** [comment] 2020-03-16 16:45
If anyone else is using anaconda/miniconda, you can setup an environment with python 3.7.

```
conda create -n gentl_37 matplotlib python=3.7
conda activate gentl_37
python -V
Python 3.7.6
pip install harvesters
Collecting harvesters
  Using cached harvesters-1.1.0-py3-none-any.whl (149 kB)
Collecting genicam>=1
  Downloading genicam-1.0.0-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 1.6 MB/s
Requirement already satisfied: numpy in c:\users\jcormier\.conda\envs\gentl_37\lib\site-packages (from harvesters) (1.18.1)
Installing collected packages: genicam, harvesters
Successfully installed genicam-1.0.0 harvesters-1.1.0
```

**Comment by kazunarikudo** [comment] 2020-03-16 16:47
@jcormier Thank you for leaving such valuable information above for other users. :-)

**Comment by kazunarikudo** [comment] 2020-03-16 16:51
One more note: Python 3.4 will not be supported by the `genicam` package since the next release because it's not been maintained by the Python committee.

**Comment by kazunarikudo** [comment] 2020-03-17 00:52
I will close this ticket once the next version of the `genicam` package is uploaded to PyPI. Any additional comment is not required since the following plan has been clearly stated. Thank you. /Kazunari

**Comment by pwijethunga-MSD** [comment] 2020-04-16 11:38
I am getting the error even with python 3.7. Any suggestion ?

**Comment by kazunarikudo** [comment] 2020-04-17 08:29
@pwijethunga-MSD Hi. So could you fill up with the following items, please?
* OS and its version:
* Architecture of the PC:
* Python distribution and its version:
Note that Harvester only supports 64-bit architectures as of today.

**Comment by pwijethunga-MSD** [comment] 2020-04-17 11:17
> * OS and its version: Windows 10 Enterprise 
> * Architecture of the PC: 64bit OS, x64 bit OS
> * Python distribution and its version: Tries Python 3.7.6, and 3.6.10 both with anaconda environment
>   Note that Harvester only supports 64-bit architectures as of today.

Thanks in advance!

**Comment by pwijethunga-MSD** [comment] 2020-04-17 11:25
This is the error I get after installing GenTL and trying to install:
After installing GenTL I am still getting the error when trying to install Harvesters. Error is below
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)'))': /simple/harvesters/
Could not fetch URL https://pypi.org/simple/harvesters/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/harvesters/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)'))) - skipping
ERROR: Could not find a version that satisfies the requirement harvesters (from versions: none)
ERROR: No matching distribution found for harvesters
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)'))) - skipping

This is may be because of connection issue? If so how to get the file saved to somewhere else and install from local place?

**Comment by kazunarikudo** [comment] 2020-04-17 12:48
@pwijethunga-MSD Hi. As you are guessing, the issue is coming from the connection issue. Maybe you should check the proxy setting if you are making a try from your office and your IT people might help you. One more thing, if you are trying to install Harvester through Cygwin, then it will not work because Cygwin GCC is not supported by GenICam. If you can visit the PyPI page, then you should check the left pane. There should be a link that navigates you to the page where you can download Python wheels. Once you get a proper wheel, then you'd be able to manually install it executing the `pip` command. Check out the `pip` manual if you are curious to make it by yourself. Good luck. /Kazunari

**Comment by zungam** [comment] 2020-05-25 16:59
Any word from genicam when it will arrive? I kinda need to use multithreading.shared_memory for python 3.8 with Harvesters. If you dont know, can I contact them and ask?

**Comment by kazunarikudo** [comment] 2020-05-26 00:03
@zungam Hi. We as the GenICam committee will have a conference call tomorrow. Probably we would discuss the next release. I will update you once the information turned official. /Kazunari

**Comment by kazunarikudo** [comment] 2020-05-26 02:39
@zungam Hi again, This is just for your information but I am the one who is actually developing/maintaining the `genicam` package but we as the GenICam committee have to synchronize other relevant modules to have one release that is twice per a year in general. I am sorry for the inconvenience for you but I hope you understand our release procedure.

**Comment by kazunarikudo** [comment] 2020-05-28 01:09
In the Spring IVSM we had on May 27, 2020, we as the GenICam committee concluded the next release date will be set during the coming Fall IVSM. That would imply the next release will be around the end of 2020 or early 2021. Thank you for your understanding. Even though the decision itself cannot be changed but if the decision makes your project turn a crap, please let me know the reason as clearly and shortly as possible. If it is much valuable to other users, there could be a chance to have another option.

**Comment by jcormier** [comment] 2020-05-28 13:43
Is it not possible up to update the pip package to support the newer python without updating the harvesters version? This seems pretty odd.

**Comment by kazunarikudo** [comment] 2020-05-28 13:51
For Harvester, it works for any version that is greater than or equal to 3.4 because it's a pure Python package. However, the `genicam` package is CPython version dependent; the dependency is coming from the tool I used to create the Python binding and we cannot get rid of it as long as we rely on the tool. Sorry for the inconvenience but this is the reality.

**Comment by jcormier** [comment] 2020-05-28 14:03
Your right I should have said genicam instead of harvesters.

Sorry just trying to understand. So the CPython tool for genicam your using doesn't support Python 3.8 yet?

**Comment by kazunarikudo** [comment] 2020-05-28 14:19
Thank you for your reply.

> So the CPython tool for genicam your using doesn't support Python 3.8 yet?

The tool itself does not rule the Python versions that we can build for rather it just depends on the decision who builds the binary. I have already updated the code so that the `genicam` package supports Python 3.8. However, the package depends on, i.e., links to the GenICam GenApi reference implementation as well, that is implemented in C++, and we as the GenICam committee have to synchronize many relevant libraries and their versions. I mean even if I updated the `genicam` package I cannot release only the package because the linked reference implementation is just an intermediate version before the next official release. Therefore, as a result, we have to wait for the right timing to release.

I'm seeing a disadvantage in the design of the `genicam` package from a dependency point of view but there's no easy fix for now, to be honest.

**Comment by jcormier** [comment] 2020-05-28 17:15
Thanks for the explanation.

Gotcha so the current code which supports 3.8, is linked against a genicam version that hasn't been released yet. So a new release can't be kicked off.

Would it be possible to branch at the point where it was still using the older "current" genicam version and add the 3.8 fixes.  And release from there?  Just brainstorming ideas.

**Comment by kazunarikudo** [comment] 2020-05-28 19:17
Excuse me, I’m not yet getting your idea but do you mean you are expecting a way that prevent a Python 3.8 environment installs Harvester through the pip command?

**Comment by jcormier** [comment] 2020-05-28 20:16
I don't understand your question.

I'm just trying to brainstorm ideas on how we can get a Python 3.8 package released using the older (already released) genicam c++ version.

**Comment by zungam** [comment] 2020-06-05 17:55
Hi, @kazunarikudo, thankyou for taking your time to write to us, and thankyou for developing genicam. 

> Even though the decision itself cannot be changed but if the decision makes your project turn a crap, please let me know the reason as clearly and shortly as possible. 

I see. I am currently working on a highly process dependent computer vision task which needs shared_memory in order to work together in parallel. Our solution is primarily on Windows, which means I can't use the fast [Ray](https://github.com/ray-project/ray) library to do fast shared memory, luckily python 3.8 vanilla included shared_memory module which is fast, but Harvesters won't install with 3.8. These means I'm kinda stuck for now, and our camera prototype launch is this summer. I will need to redo alot, or find a way to migrate to Linux.

>  I have already updated the code so that the `genicam` package supports Python 3.8. However, the package depends on, i.e., links to the GenICam GenApi reference implementation as well, that is implemented in C++ , and we as the GenICam committee have to synchronize many relevant libraries and their versions.

Does Harvesters depend on these C++ synchronizations? If the synchronizations is primarily for other use-cases than Harvesters would it be possible to release a "dumbed down" version which only works with Harvesters? :-)

**Comment by kazunarikudo** [comment] 2020-06-07 14:26
@zungam @jcormier Hello, gentlemen. I have decided to take action to have a reasonable workaround to not let both of you down. You would see the outcome in the following days and I will let you know once it turned available. One thing I would like you to understand is the workaround is a literally beta version anyway. Even if you faced consequential damage due to an issue of the binary I will not take the responsibility for the issue. Thanks. /Kazunari

**Comment by zungam** [comment] 2020-06-08 15:52
@kazunarikudo thankyou so much good sir. It will definitely aid our project to finish to our deadline! How can I show my gratitude?

**Comment by kazunarikudo** [comment] 2020-06-09 08:14
@zungam Hi.

> How can I show my gratitude?

Oh, you do not need to show me anything. Please just keep being nice to your family, colleagues, and neighbors as usual. That would be enough for me.

Regarding Python 3.8 support, I would like to help you gentlemen but also I do not want to involve unrelated people in unnecessary trouble. So I have decided to pin the `genicam` package version so that the `harvesters` package installs its version 1.0.0 as usual.

On the other hand, some additional procedures will be required if you want to use the Python 3.8 capable `genicam` package, version 1.0.1.

First, you would execute the following pip command to install Harvester:
```
$ pip install harvesters
````
Then the command will install `genicam` package version 1.0.0 from its dependency but you want to install `genicam` package version 1.0.1 in reality. So you will have to uninstall the installed `genicam` package`:
```
$ pip uninstall genicam
```
And then, now you install version 1.0.1:
```
$ pip install genicam==1.0.1
```
Would you be okay with the suggested procedures above? If you are okay, I will upload the `genicam` package to PyPI tonight.

/Kazunari.

**Comment by jcormier** [comment] 2020-06-09 14:06
Sounds good.  I wonder if running `pip install harvesters genicam==1.0.1` would prevent the need for the uninstall step.

**Comment by zungam** [comment] 2020-06-10 00:53
@kazunarikudo 

> Please just keep being nice to your family, colleagues, and neighbors as usual. That would be enough for me.

Thanks, Ill be sure to do that :)

> Would you be okay with the suggested procedures above? 

Yes thats fine by me.  Will **harvesters** and **genicam==1.0.1** be available through normal pip in a 3.8 environment then?

**Comment by kazunarikudo** [comment] 2020-06-10 00:59
@zungam Hi, thank you for your message.
> Will harvesters and genicam==1.0.1 be available through normal pip in a 3.8 environment then?

Yes, as far as I tested it with another Python package, the way you suggested work so it should work for Harvester as well.

I have just finished the preparation for the Harvester side. I will upload the `genicam` package soon but I hope you understand it'd be done by your next morning.

/Kazunari

**Comment by kazunarikudo** [comment] 2020-06-10 05:57
This is just for your information: The following command:
```
$ pip install harvesters genicam==1.0.1
```
Gives you the following message (that's just line in the whole message):
```
ERROR: harvesters 1.2.4 has requirement genicam==1.0.0, but you'll have genicam 1.0.1 which is incompatible.
```
The following command also gives us the same message:
```
$ pip install harvesters && pip uninstall genicam && pip install genicam==1.0.1
```
However, the return value of the execution is `0`, i.e., no error so I guess it does not block you anyway; I tested the commands above on a macOS machine.

Would that be okay for you gentlemen?

/Kazunari

**Comment by kazunarikudo** [comment] 2020-06-10 23:13
@zungam Hi, thank you for your reply.

> Looking at your pypi resp, there seems to be only macOS links.

That's true because I have uploaded only the macOS version for a trial and wanted to hear your opinion for a reality that I observed from the trial. You say you are okay with the finding above, I will update the Windows version (and the Linux version as well) shortly.

Regards,
Kazunari

**Comment by zungam** [comment] 2020-06-14 21:55
@kazunarikudo genicam 1.0.1 seem to be working with harvesters on windows now. Thankyou very much for your effort helping us! :-)

**Comment by kazunarikudo** [comment] 2020-06-17 23:36
@zungam You are welcome! I hope you enjoy your job with Harvester.

**Closed by kazunarikudo** 2020-06-17 23:36 UTC
Labels: genicam, good first issue
