### ISSUE TITLE
Unable to get images with a specific model of camera

### ISSUE THREAD

**Issue by seysn** [genicam/harvesters#206] opened 2020-10-23 14:36 UTC
**Describe the bug**
`ia.fetch_buffer()` returns `None` without any Exception or any logging message on my basler camera (acA2500-14gcCAR).
The camera is working fine on their proprietary software pylon viewer and with pypylon.
I managed to get images of an IDS camera with Harvesters, and I didn't get any images with harvesters_gui as well.
Maybe there's something specific on this camera to include ?
Also I can get all the settings in node_map, and modify them as much as I can, I just can't get an image.

**To Reproduce**
Get a acA2500-14gcCAR basler camera and then use the library :
```python
>>> from harvesters.core import Harvester
>>> h = Harvester()
>>> h.add_file("/opt/pylon/lib/gentlproducer/gtl/ProducerGEV.cti")
>>> h.update()
>>> h.device_info_list
[(id_='Basler acA2500-14gcCAR (24942103)', vendor='Basler', model='acA2500-14gcCAR', tl_type='GEV', user_defined_name=None, serial_number='24942103', version='107658-01')]
>>> ia = h.create_image_acquirer(id_=h.device_info_list[0].id_)
>>> ia.start_acquisition(True)
>>> buffer = ia.fetch_buffer()
>>> buffer
None
>>> ia.remote_device.node_map.Gamma.value
1.0
>>> ia.remote_device.node_map.Gamma.value = 2
>>> ia.remote_device.node_map.Gamma.value
2.0
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS (Focal Fossa)
 - Python: 3.8.5
 - Harvester: 1.2.8
 - GenTL Producer: Basler
 - Camera: acA2500-14gcCAR

**Comment by kazunarikudo** [comment] 2021-08-13 14:02
@seysn Hi, I am so sorry for having kept you waiting for a year! Did you get any updates on this? Or, have you already given up using Harvester? Regards, Kazunari.

**Comment by seysn** [comment] 2021-08-13 14:26
@kazunarikudo Hi, if I remember correctly, I had two models of basler camera, but only one of them worked with Harvesters. Since I needed a library that works with both, I stayed with the official driver of basler.
This model seems uncommon, so I was not surprised to be the only one affected by this bug.

**Comment by kazunarikudo** [comment] 2021-08-13 14:37
@seysn Thank you for your reply. I am going to close this ticket but please feel free to come back anytime when you need to work with Harvester! There should still be hope if the issue is not a crash that is caused by segfault.

**Closed by kazunarikudo** 2021-08-13 14:37 UTC
