### ISSUE TITLE
Problem with ximea camera

### ISSUE THREAD

**Issue by TobiasBaasch** [genicam/harvesters#257] opened 2021-08-24 12:49 UTC
**Describe the Bug**
I would like to use a Basler and a Ximea camera for my application. My code with the Matrix Vision Producer works pretty well with the Basler camera. The problem occurs with the Ximea camera. 
Here the first problem is that I cannot use the Ximea camera with the Matrix Vision Producer because the Producer does not recognize the Ximea camera.
For this reason, I use the Producer directly from Ximea.
There the camera is recognized and I can also grab a picture. But when I call the stop_acquisition() function the following error occurs:

`SystemError: <built-in function DataStream__revoke_buffer> returned NULL without setting an error`

**To Reproduce**
```
from harvesters.core import Harvester
harvester = Harvester()
harvester.add_file(r"C:\XIMEA\GenTL Producer\64bit\ximea.gentl.64.cti")
harvester.update()
cam_serial_number       = harvester.device_info_list[0].serial_number
cam = harvester.create_image_acquirer(serial_number = cam_serial_number)
cam.start_acquisition()
with cam.fetch_buffer() as buffer:
    print(buffer)
cam.stop_acquisition() #<--- this is where the error occurs
cam.destroy()
harvester.reset() 
```

**Expected Behavior**
I would have thought that I could use the code normally for the Ximea camera as with the Basler camera but with a different producer.
I don't know what to change to make it work or if there is a bug somewhere.

**Configuration**

 - OS: [Windows 10]
 - Python: [3.8.10]
 - Harvester: [1.3.2]
 - GenTL Producer: [Ximea/Matrix Vision]
 - Camera: [Ximea]

**Comment by kazunarikudo** [comment] 2021-08-24 13:38
@TobiasBaasch Hi,
> I cannot use the Ximea camera with the Matrix Vision Producer

I do not know which camera from Ximea you are using now but I'd guess MATRIX VISION should be able to work with theirs. A scenario that I can imagine if the camera is a U3V model is... is Ximea driver still being attached to the device? Regards, Kazunari.

**Comment by kazunarikudo** [comment] 2021-08-24 13:41
By the way, no matter where the root cause was, the issue you are facing would not be fixed by Harvester itself. I would recommend you to not expect the Ximea TL-based solution. Let's try to get your Ximea camera working with MATRIX VISION TL.

**Comment by TobiasBaasch** [comment] 2021-08-24 14:09
Hey @kazunarikudo,
thanks for the quick feedback. 

> I do not know which camera from Ximea you are using now

I am using the Ximea xiQ MQ013CG-E2 which is a USB3 Vision camera.

> is Ximea driver still being attached to the device

I think the driver is not attached to the camera. When I connect the camera to the PC without the XIMEA Windows Software Package installed, the camera cannot connect to the PC.

> Let's try to get your Ximea camera working with MATRIX VISION TL.

Since the two producers differ, this would also be the better solution for me

**Comment by kazunarikudo** [comment] 2021-08-24 14:16
Thank you for your reply.
> When I connect the camera to the PC without the XIMEA Windows Software Package installed, the camera cannot connect to the PC.

Wow, really? Do their cameras run on only the computers that have installed their software package?!

**Comment by TobiasBaasch** [comment] 2021-08-24 14:25
> Don't their cameras run on any computers that have not installed their software package?!

I have tried it on three different PCs now. If nothing else is installed, the camera keeps connecting and disconnecting within a few seconds. I have not found a standalone driver outside of the software package yet either.
But maybe I am missing something big

**Comment by kazunarikudo** [comment] 2021-08-24 14:47
Could you check again if MATRIX VISION's U3V device driver has been attached to the target camera, please? I guess you can do that for at least Basler's one so you have confirmed that you can acquire images from the Basler camera. I would expect that you can do this for Ximea's one as well.

**Comment by TobiasBaasch** [comment] 2021-08-24 15:40
> Could you check again if MATRIX VISION's U3V device driver has been attached to the target camera, please?

Where can i download the MATRIX VISION's U3V device driver and how can i check if the driver is attached? 
This is what i get from the wxPropView info:

<img width="477" alt="Unbenannt2" src="https://user-images.githubusercontent.com/69963697/130646531-8894a3d7-de78-4cff-9d1b-ebe4b230f2e9.PNG">

and this is the current driver for the ximea camera

<img width="550" alt="Unbenannt" src="https://user-images.githubusercontent.com/69963697/130647016-f3204688-099f-42d2-a228-dbbc60b45fcc.PNG">

>  that you can acquire images from the Basler camera

I am using the Basler acA2500-14gc GigE Vision Camera and i can acquire images from it.

**Comment by kazunarikudo** [comment] 2021-08-24 15:47
I can't precisely recall but MATRIX VISION should install a utility application that shows the U3V capable devices in the system and you can attach their driver for an arbitrary device. The screenshot should be just a view from MATRIX VISION's app as a GenTL consumer. GigE Vision devices do not require U3V style drivers so you can use them without any extra effort that you need to work for U3V devices. Again, please find a way to attach MATRIX VISION's U3V driver to the Ximea U3V camera. Good luck!

**Closed** 2021-08-30 13:19 UTC
